services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
    volumes:
      - .:/app
    command: ["yarn", "start:dev"]
